sudo: false
language: ruby
bundler_args: --without development
script:
  - rake
rvm:
  - 1.9.3
  - 2.1
  - 2.2
  - rbx
  - jruby-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx
notifications:
  email: false
